let posts = [
    {
        name:"Rick Sanchez",
        icon:"https://e7.pngegg.com/pngimages/286/70/png-clipart-rick-sanchez-morty-smith-pocket-mortys-rick-morty.png",
        nickname: "@Rick",
        content: " And that's why I always say, shum-shum-schlippety-dop!",
        image: "https://upload.wikimedia.org/wikipedia/ru/a/a6/Rick_Sanchez.png",
        date: "January 26, 1943",
        hearts: 360,
    },
    {
        name:"Morty Smith",
        icon:"https://www.freepnglogos.com/uploads/rick-and-morty-png/rick-and-morty-morty-face-kushmastafresh-deviantart-27.png",
        nickname: "@Morty",
        content: " Nobody exists on purpose. Nobody belongs anywhere. We’re all going to die. Come watch TV.",
        image: "https://upload.wikimedia.org/wikipedia/ru/c/c3/Morty_Smith.png",
        date: "September 19th, 2002",
        hearts: 249,
    },
    {
        name:"Gerald Jerry Smith",
        icon:"https://img.icons8.com/plasticine/512/jerry-smith.png",
        nickname: "@Jerry",
        content: " When you’re not sure what you do for a living, you can make your own rules.",
        image: "https://upload.wikimedia.org/wikipedia/en/a/a6/Jerry_Smith_%28Rick_and_Morty%29.png",
        date: "April, 20th 1982",
        hearts: 186,
    },
    {
        name:"Summer Smith",
        icon:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR_2jQb238NWObJz8M5xcLjFKDDN0yfdZP4g&usqp=CAU",
        nickname: "@Summer",
        content: " No Wonder You're Constantly Fighting With Eachother And Behind Schedule",
        image: "https://upload.wikimedia.org/wikipedia/en/9/9f/Summer_Smith.png",
        date: "December 2nd, 1997",
        hearts: 177,
    },
    {
        name:"Bethany Smith",
        icon:"https://img.icons8.com/plasticine/512/beth-smith.png",
        nickname: "@Bethany",
        content: " You can’t make people like you. You just have to wait for hating you to bore them.",
        image: "https://upload.wikimedia.org/wikipedia/en/5/58/Beth_Smith.png",
        date: "November 19th, 1982",
        hearts: 158,
    },
    {
        name:"Space Cruiser",
        icon:"https://cdn140.picsart.com/287486530008211.png",
        nickname: "@Spaceship",
        content: " You can’t make people like you. You just have to wait for hating you to bore them.",
        image: "http://cdn.shopify.com/s/files/1/0337/2993/7548/products/21cnrm00026a-002-rick-cool-ship-172-swatch_1024x.jpg?v=1645751938",
        date: "January 26, 1967",
        hearts: 235,
    }
];
export {posts};